services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: CatalogAPI/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: Services/Catalog/WebApplication1/Dockerfile
